# 1. Notice the database name is now 'ecommerce_db'
spring.datasource.url=jdbc:mysql://localhost:3306/ecommerce_db?allowPublicKeyRetrieval=true&useSSL=false

# 2. Username is still root, but Password is 'rootpassword'
spring.datasource.username=root
spring.datasource.password=rootpassword

# 3. Magic settings
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true