spring.application.name=ecommerce-api
# 1. Where is the database? (Connecting to your Docker MySQL container)
spring.datasource.url=jdbc:mysql://localhost:3306/ecommerce?allowPublicKeyRetrieval=true&useSSL=false

# 2. Database Username & Password (Standard local dev defaults)
spring.datasource.username=root
spring.datasource.password=root

# 3. 🚨 The Magic Setting: This tells JPA to automatically create/update your tables!
spring.jpa.hibernate.ddl-auto=update

# 4. Show us the translated SQL in the terminal so we can learn how it works
spring.jpa.show-sql=true